// Bundles `src/main.ts` → `main.js` for Obsidian: CJS output, `.html` imports as strings, Obsidian/electron externals.
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */";

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  loader: { ".html": "text" },
  external: ["obsidian", "electron", ...builtins],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js"
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
